theme: jekyll-theme-hacker
google_analytics: UA-163222683-1
layout: post

lsi: false
safe: true
source: jekyll_docs
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
